#!/bin/bash
## creadir.sh for creadir in /home/debrau_c/bin
## 
## Made by debrau_c
## Login   <debrau_c@epitech.net>
## 
## Started on  Mon Feb  1 09:58:36 2016 debrau_c
## Last update Tue Feb 21 18:32:55 2017 debrau_c
##
me=carl.debrauwere@epitech.eu
repo=debrau_c
blih -u $me repository create "$1"
blih -u $me repository setacl "$1" ramassage-tek r
git clone git@git.epitech.eu:/$repo/"$1"
blih -u $me repository getacl "$1"
