#!/bin/bash
## curr_dir.sh for azd in /home/debrau_c/bin
## 
## Made by debrau_c
## Login   <carl.debrauwere@epitech.eu>
## 
## Started on  Tue Mar 28 10:42:57 2017 debrau_c
## Last update Tue Mar 28 10:43:07 2017 debrau_c
##

cd $CUR_DIR
