#!/bin/sh
## getclass.sh for azd in /home/debrau_c/bin
## 
## Made by Carl DEBRAUWERE
## Login   <debrau_c@epitech.net>
## 
## Started on  Mon Jan 16 09:33:45 2017 Carl DEBRAUWERE
## Last update Sun Jan 22 23:37:08 2017 Carl DEBRAUWERE
##
##
##
##  Creer une classe en cpp avec le header
##


usage(){
    echo -e "Usage : $1 Class1 Class2 [-options] arg1 arg2
\t-i : personnal include
\t-I : system include"
    }
epitech_head(){
	echo "/*
** $1 for azd in /home/debrau_c/bin
** Made by Carl DEBRAUWERE
** Login   <debrau_c@epitech.net>
** 
** Started on  Mon Jan 16 09:33:45 2017 Carl DEBRAUWERE
** Last update Mon Jan 16 09:33:45 2017 Carl DEBRAUWERE
*/" >> $1
}

##Gestion des include

starti=0
startI=0
j=0
for i in "$@";do
    if [ ${i:0:1} == "-" ];then
	let "startI=0"
	let "starti=0"
    fi
    if [ $starti -eq 1 ];then
	includei["$j"]=$i
	let "j=$j+1"
    fi
    if [ $startI -eq 1 ];then
	includeI["$j"]=$i
	let "j=$j+1"
    fi
    if [ ${i:0:1} == "-" ];then
	let "startI=0"
	let "starti=0"
	j=0
	if [ ${i:1:2} == "i" ];then
	    let "starti=1"
	elif [ ${i:1:2} == "I" ];then
	    let "startI=1"
	fi
    fi
done
i=0

put_include(){
    x=($1)
    file=$2
    opt=$3
    if [ $opt -eq 0 ]; then
	for s in "${x[@]}";do
	    echo "#include \"$s.hh\"" >> $file
	done
    else
	for s in "${x[@]}";do
	    echo "#include <$s>" >> $file
	done
    fi
}

if [ "$#" -lt 1 ];then
    usage $0
    exit 1
fi

for i in "$@";do
    if [ -z $i ];then
	0 = 0;
    elif [ ${i:0:1} == "-" ];then
	exit 0
    else
	header=$i".hh"
	source=$i".cpp"
	epitech_head $header;
	echo>> $header
	echo -n "#ifndef _">> $header
	echo $i"_H_"| tr '[:lower:]' '[:upper:]' >> $header
	echo -n "# define _">>  $i".hh"
	echo $i"_H_"| tr '[:lower:]' '[:upper:]'>> $header
	echo >> $header;
	put_include "${includeI[*]}" $header 1
	put_include "${includei[*]}" $header 0
	echo >> $header
	echo "class $i{">> $header
	echo "public:">> $header
	echo -e "  $i();" >> $header
	echo -e "  ~$i();" >> $header
	echo "};" >> $header
	echo >> $header;
	echo "#endif /* $i */" >> $header
	epitech_head $source;
	echo >> $source;
	echo "#include \"$header\"" >> $source

	echo >> $source;
	echo "$i::$i(){

}" >> $source;
	echo "$i::~$i(){

}" >> $source;
    fi
done
