#!/bin/sh

echo -n "Type name of project :"
read project
echo -n "Type name of file :"
read file
echo "/* File : $file 
** For project : $project
** Made at $(date)
## Last update Sun Jan  8 18:02:45 2017 Carl DEBRAUWERE
**
** by : ╔═╗┌─┐┬─┐┬    ╔╦╗┌─┐┌┐ ┬─┐┌─┐┬ ┬┬ ┬┌─┐┬─┐┌─┐
**	║  ├─┤├┬┘│     ║║├┤ ├┴┐├┬┘├─┤│ ││││├┤ ├┬┘├┤ 
**	╚═╝┴ ┴┴└─┴─┘  ═╩╝└─┘└─┘┴└─┴ ┴└─┘└┴┘└─┘┴└─└─┘
*/" > $file
