#!/bin/bash
## pushit.sh for azd in /home/debrau_c/bin
## 
## Made by Carl DEBRAUWERE
## Login   <debrau_c@epitech.net>
## 
## Started on  Tue Jan  3 16:05:25 2017 Carl DEBRAUWERE
## Last update Sat Apr  8 00:57:56 2017 debrau_c
##
if [ -e Makefile ];then
    make re &> /dev/null
    if [ $? -ne 0 ];then
	echo "Project doesn't compile !! Little noob."
	exit
    fi
fi

make fclean &> /dev/null
${HOME}/bin/mr_clean
git add --all
if [ $@ -e 1 ]; then
    git commit -am "default message from'$0'-script"
else
    git commit -am $@
fi
git push origin master
