#!/bin/bash
## pushit.sh for azd in /home/debrau_c/bin
## 
## Made by Carl DEBRAUWERE
## Login   <debrau_c@epitech.net>
## 
## Started on  Tue Jan  3 16:05:25 2017 Carl DEBRAUWERE
## Last update Wed Mar  1 23:03:39 2017 debrau_c
##

make re &> /dev/null
if [ $? -ne 0 ];then
    echo "Project doesn't compile !! Little noob."
    exit
fi
make fclean &> /dev/null
${HOME}/bin/mr_clean
git add --all
if [ -z $1 ]; then
    git commit -am "default message from'$0'-script"
else
    git commit -am $1
fi
git push origin master
